services:
  api:
    build: 
      context: .
      dockerfile: api/Dockerfile
    container_name: docstream-api
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
    depends_on:
      rabbitmq:
        condition: service_healthy
  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    container_name: docstream-worker
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: docstream-rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 10