version: '3.8'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
  radbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest